const keywords = [
    "Singapore Port",
    "Singapore Maritime",
    "Singapore Maritime Port Authority",
    "Port Authority of Singapore",
    "Port Authority Singapore",
    "Singapore Port Authority",
    "Singapore Straits",
    "Pedra Branca",
    "Costa Fortuna",
    "Sea Chokepoints",
    "Floating+accomodations+Singapore",
    "Crew+change+Singapore",
    "Covid-19+Singapore+maritime",
    "Sea Robberies+Singapore",
    "Piracy+Singapore",
    "Oil spill+Singapore",
    "Marine+pollution+Singapore",
    "Cyber+security+Singapore+port",
    "Cyber+hacking+Singapore+port",
    "Singapore+port+open",
    "Ship+Capsize+Singapore",
    "Ship+Collision+Singapore",
    "Ship+stuck+Singapore",
    "MaritimeSG",
    "Port Dues",
    "Carbon tax+Singapore",
    "Craft license",
    "Merchant Shipping Act",
    "Merchant Shipping CLCO Act",
    "Merchant Shipping MLC Act",
    "Merchant Shipping Wreck Removal Act",
    "MPA Act",
    "Prevention of Pollution of the Sea Act",
    "SOLAS",
    "Regional Ferry Services Operator License",
    "Admiralty+Jurisdiction+Singapore",
    "Sanction+ship+Singapore",
    "Sand reclamation",
    "Tuas Port",
    "Tuas+MRT+bus",
    "Sultan Shoal",
    "Compliance+IMO2020",
    "Decarbonisation+IMO2030",
    "Bunkering+license+revocation",
    "MFM+tampering",
    "Insufficient+bunker+suppliers",
    "Insufficient+bunker+craft",
    "Contaminated+bunker+Singapore",
    "Oil+theft",
    "Singapore+registered+ship",
    "Singapore+flagged+ship",
]

exports.keywords = keywords;